#!/usr/bin/env bash
set -euo pipefail

dry_run=false
if [[ "${1-}" == "--dry-run" ]]; then
  dry_run=true
elif [[ "${1-}" == "-h" || "${1-}" == "--help" ]]; then
  echo "Usage: $0 [--dry-run]"
  exit 0
elif [[ -n "${1-}" ]]; then
  echo "Unknown argument: $1" >&2
  echo "Usage: $0 [--dry-run]" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v uv >/dev/null 2>&1; then
  echo "Error: 'uv' not found in PATH. Install uv first: https://docs.astral.sh/uv/" >&2
  exit 1
fi

shell_name="${SHELL##*/}"
case "$shell_name" in
  zsh)
    rc_file="$HOME/.zshrc"
    ;;
  bash)
    rc_file="$HOME/.bashrc"
    ;;
  *)
    rc_file="$HOME/.zshrc"
    echo "Unsupported shell '$shell_name'; defaulting to zsh rc: $rc_file"
    ;;
esac

start_marker="# >>> sparv-uv-completion >>>"
end_marker="# <<< sparv-uv-completion <<<"

snippet=$(cat <<EOF
$start_marker
# Auto-generated by scripts/install-shell-completion.sh
# Repo: $REPO_ROOT
# Default Sparv data dir for this repo (override by setting SPARV_DATADIR before sourcing).
export SPARV_DATADIR="\${SPARV_DATADIR:-$REPO_ROOT/.sparv-data}"

sparv() {
  uv run --project "$REPO_ROOT" python -m sparv "\$@"
}

if [ -n "\${ZSH_VERSION-}" ]; then
  autoload -U +X bashcompinit && bashcompinit
fi

if uv run --project "$REPO_ROOT" python -m sparv --version >/dev/null 2>&1; then
  eval "\$(uv run --project '$REPO_ROOT' python -m sparv autocomplete --enable)"
fi
$end_marker
EOF
)

if $dry_run; then
  if [[ -f "$rc_file" ]] && grep -Fq "$start_marker" "$rc_file"; then
    echo "[dry-run] Would update existing Sparv completion block in $rc_file"
  else
    echo "[dry-run] Would append Sparv completion block to $rc_file"
  fi
  echo
  echo "[dry-run] Block content:"
  echo "$snippet"
  exit 0
fi

mkdir -p "$(dirname "$rc_file")"
touch "$rc_file"
mkdir -p "$REPO_ROOT/.sparv-data"

if grep -Fq "$start_marker" "$rc_file"; then
  python3 - "$rc_file" "$start_marker" "$end_marker" "$snippet" <<'PY'
from pathlib import Path
import sys

rc_file, start_marker, end_marker, snippet = sys.argv[1:5]
path = Path(rc_file)
text = path.read_text(encoding="utf-8")

start_idx = text.find(start_marker)
if start_idx == -1:
    new_text = text.rstrip("\n") + "\n\n" + snippet + "\n"
else:
    end_idx = text.find(end_marker, start_idx)
    if end_idx == -1:
        new_text = text[:start_idx].rstrip("\n") + "\n\n" + snippet + "\n"
    else:
        end_idx = end_idx + len(end_marker)
        new_text = text[:start_idx].rstrip("\n") + "\n\n" + snippet + text[end_idx:]

path.write_text(new_text, encoding="utf-8")
PY
  echo "Updated existing Sparv completion block in $rc_file"
else
  printf "\n%s\n" "$snippet" >> "$rc_file"
  echo "Added Sparv completion block to $rc_file"
fi

echo
echo "Next steps:"
echo "  1) Reload shell config: source \"$rc_file\""
echo "  2) Verify data dir: echo \"\$SPARV_DATADIR\""
echo "  3) Initialize data dir once: uv run --project \"$REPO_ROOT\" python -m sparv setup --dir \"$REPO_ROOT/.sparv-data\""
echo "     (or from repo root: make completion-setup-datadir)"
echo "  4) Use: sparv --help"
echo "  5) Tab-complete works on: sparv ..."
